In [ ]:
import numpy as np
import pandas as pd
from scipy import stats

# Load dataset (replace 'your_dataset.csv' with the path to your dataset)
df = pd.read_csv('/content/fraudTrain.csv')
rows_with_nan = df[df.isnull().any(axis=1)]
print(df)


# Select the specific column(s) you want to analyze (replace 'column_name' with your column name)

           Index trans_date_trans_time        cc_num  \
0              0         1/1/2019 0:00  2.703190e+15
1              1         1/1/2019 0:00  6.304230e+11
2              2         1/1/2019 0:00  3.885950e+13
3              3         1/1/2019 0:01  3.534090e+15
4              4         1/1/2019 0:03  3.755340e+14
...          ...                   ...           ...
1048570  1048570       3/10/2020 16:07  6.011980e+15
1048571  1048571       3/10/2020 16:07  4.839040e+15
1048572  1048572       3/10/2020 16:08  5.718440e+11
1048573  1048573       3/10/2020 16:08  4.646850e+18
1048574  1048574       3/10/2020 16:08  2.283740e+15

                                   merchant        category     amt  \
0                fraud_Rippin, Kub and Mann        misc_net    4.97
1           fraud_Heller, Gutmann and Zieme     grocery_pos  107.23
2                      fraud_Lind-Buckridge   entertainment  220.11
3        fraud_Kutch, Hermiston and Farrell   gas_transport   45.00
4                       fraud_Keeling-Crist        misc_pos   41.96
...                                     ...             ...     ...
1048570                     fraud_Fadel Inc  health_fitness   77.00
1048571    fraud_Cremin, Hamill and Reichel        misc_pos  116.94
1048572  fraud_O'Connell, Botsford and Hand            home   21.27
1048573              fraud_Thompson-Gleason  health_fitness    9.52
1048574                 fraud_Buckridge PLC        misc_pos    6.81

             first      last gender                            street  ...  \
0         Jennifer     Banks      F                    561 Perry Cove  ...
1        Stephanie      Gill      F      43039 Riley Greens Suite 393  ...
2           Edward   Sanchez      M          594 White Dale Suite 530  ...
3           Jeremy     White      M       9443 Cynthia Court Apt. 038  ...
4            Tyler    Garcia      M                  408 Bradley Rest  ...
...            ...       ...    ...                               ...  ...
1048570      Haley    Wagner      F            05561 Farrell Crescent  ...
1048571   Meredith  Campbell      F               043 Hanson Turnpike  ...
1048572      Susan     Mills      F                  005 Cody Estates  ...
1048573      Julia      Bell      F               576 House Crossroad  ...
1048574    Shannon  Williams      F  9345 Spencer Junctions Suite 183  ...

             lat      long  city_pop                                job  \
0        36.0788  -81.1781      3495          Psychologist, counselling
1        48.8878 -118.2105       149  Special educational needs teacher
2        42.1808 -112.2620      4154        Nature conservation officer
3        46.2306 -112.1138      1939                    Patent attorney
4        38.4207  -79.4629        99     Dance movement psychotherapist
...          ...       ...       ...                                ...
1048570  39.0305  -76.5515     92106    Accountant, chartered certified
1048571  41.1826  -92.3097      1583                         Geochemist
1048572  38.2507  -85.7476    736284              Engineering geologist
1048573  40.7320  -73.1000      4056                  Film/video editor
1048574  34.0770  -84.3033    165556                     Prison officer

                dob                         trans_num   unix_time  merch_lat  \
0          3/9/1988  0b242abb623afc578575680df30655b9  1325376018  36.011293
1         6/21/1978  1f76529f8574734946361c461b024d99  1325376044  49.159047
2         1/19/1962  a1a22d70485983eac12b5b88dad1cf95  1325376051  43.150704
3         1/12/1967  6b849c168bdad6f867558c3793159a81  1325376076  47.034331
4         3/28/1986  a41d7549acf90789359a9aa5346dcb46  1325376186  38.674999
...             ...                               ...         ...        ...
1048570   5/28/1943  45ecd198c65e81e597db22e8d2ef7361  1362931649  38.779464
1048571   6/28/1999  c00ce51c6ebb7657474a77b9e0b51f34  1362931670  41.400318
1048572    4/2/1952  17c9dc8b2a6449ca2473726346e58e6c  1362931711  37.293339
1048573   6/25/1990  5ca650881b48a6a38754f841c23b77ab  1362931718  39.773077
1048574  12/27/1997  8d0a575fe635bbde12f1a2bffc126731  1362931730  33.601468

         merch_long  is_fraud
0        -82.048315         0
1       -118.186462         0
2       -112.154481         0
3       -112.561071         0
4        -78.632459         0
...             ...       ...
1048570  -76.317042         0
1048571  -92.726724         0
1048572  -84.798122         0
1048573  -72.213209         0
1048574  -83.891921         0

[1048575 rows x 23 columns]

In [ ]:
df.head()

,Index,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,...,lat,long,city_pop,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud
0,0,1/1/2019 0:00,2.703190e+15,"fraud_Rippin, Kub and Mann",misc_net,4.97,Jennifer,Banks,F,561 Perry Cove,...,36.0788,-81.1781,3495,"Psychologist, counselling",3/9/1988,0b242abb623afc578575680df30655b9,1325376018,36.011293,-82.048315,0
1,1,1/1/2019 0:00,6.304230e+11,"fraud_Heller, Gutmann and Zieme",grocery_pos,107.23,Stephanie,Gill,F,43039 Riley Greens Suite 393,...,48.8878,-118.2105,149,Special educational needs teacher,6/21/1978,1f76529f8574734946361c461b024d99,1325376044,49.159047,-118.186462,0
2,2,1/1/2019 0:00,3.885950e+13,fraud_Lind-Buckridge,entertainment,220.11,Edward,Sanchez,M,594 White Dale Suite 530,...,42.1808,-112.2620,4154,Nature conservation officer,1/19/1962,a1a22d70485983eac12b5b88dad1cf95,1325376051,43.150704,-112.154481,0
3,3,1/1/2019 0:01,3.534090e+15,"fraud_Kutch, Hermiston and Farrell",gas_transport,45.00,Jeremy,White,M,9443 Cynthia Court Apt. 038,...,46.2306,-112.1138,1939,Patent attorney,1/12/1967,6b849c168bdad6f867558c3793159a81,1325376076,47.034331,-112.561071,0
4,4,1/1/2019 0:03,3.755340e+14,fraud_Keeling-Crist,misc_pos,41.96,Tyler,Garcia,M,408 Bradley Rest,...,38.4207,-79.4629,99,Dance movement psychotherapist,3/28/1986,a41d7549acf90789359a9aa5346dcb46,1325376186,38.674999,-78.632459,0

In [ ]:
df.drop(df.columns[:1], axis=1, inplace=True)
df.head()

,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,city,...,lat,long,city_pop,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud
0,1/1/2019 0:00,2.703190e+15,"fraud_Rippin, Kub and Mann",misc_net,4.97,Jennifer,Banks,F,561 Perry Cove,Moravian Falls,...,36.0788,-81.1781,3495,"Psychologist, counselling",3/9/1988,0b242abb623afc578575680df30655b9,1325376018,36.011293,-82.048315,0
1,1/1/2019 0:00,6.304230e+11,"fraud_Heller, Gutmann and Zieme",grocery_pos,107.23,Stephanie,Gill,F,43039 Riley Greens Suite 393,Orient,...,48.8878,-118.2105,149,Special educational needs teacher,6/21/1978,1f76529f8574734946361c461b024d99,1325376044,49.159047,-118.186462,0
2,1/1/2019 0:00,3.885950e+13,fraud_Lind-Buckridge,entertainment,220.11,Edward,Sanchez,M,594 White Dale Suite 530,Malad City,...,42.1808,-112.2620,4154,Nature conservation officer,1/19/1962,a1a22d70485983eac12b5b88dad1cf95,1325376051,43.150704,-112.154481,0
3,1/1/2019 0:01,3.534090e+15,"fraud_Kutch, Hermiston and Farrell",gas_transport,45.00,Jeremy,White,M,9443 Cynthia Court Apt. 038,Boulder,...,46.2306,-112.1138,1939,Patent attorney,1/12/1967,6b849c168bdad6f867558c3793159a81,1325376076,47.034331,-112.561071,0
4,1/1/2019 0:03,3.755340e+14,fraud_Keeling-Crist,misc_pos,41.96,Tyler,Garcia,M,408 Bradley Rest,Doe Hill,...,38.4207,-79.4629,99,Dance movement psychotherapist,3/28/1986,a41d7549acf90789359a9aa5346dcb46,1325376186,38.674999,-78.632459,0

In [ ]:
df['trans_date_trans_time'] = pd.to_datetime(df['trans_date_trans_time'])
print(df.dtypes['trans_date_trans_time'])
df.head()

datetime64[ns]

,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,city,...,lat,long,city_pop,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud
0,2019-01-01 00:00:00,2.703190e+15,"fraud_Rippin, Kub and Mann",misc_net,4.97,Jennifer,Banks,F,561 Perry Cove,Moravian Falls,...,36.0788,-81.1781,3495,"Psychologist, counselling",3/9/1988,0b242abb623afc578575680df30655b9,1325376018,36.011293,-82.048315,0
1,2019-01-01 00:00:00,6.304230e+11,"fraud_Heller, Gutmann and Zieme",grocery_pos,107.23,Stephanie,Gill,F,43039 Riley Greens Suite 393,Orient,...,48.8878,-118.2105,149,Special educational needs teacher,6/21/1978,1f76529f8574734946361c461b024d99,1325376044,49.159047,-118.186462,0
2,2019-01-01 00:00:00,3.885950e+13,fraud_Lind-Buckridge,entertainment,220.11,Edward,Sanchez,M,594 White Dale Suite 530,Malad City,...,42.1808,-112.2620,4154,Nature conservation officer,1/19/1962,a1a22d70485983eac12b5b88dad1cf95,1325376051,43.150704,-112.154481,0
3,2019-01-01 00:01:00,3.534090e+15,"fraud_Kutch, Hermiston and Farrell",gas_transport,45.00,Jeremy,White,M,9443 Cynthia Court Apt. 038,Boulder,...,46.2306,-112.1138,1939,Patent attorney,1/12/1967,6b849c168bdad6f867558c3793159a81,1325376076,47.034331,-112.561071,0
4,2019-01-01 00:03:00,3.755340e+14,fraud_Keeling-Crist,misc_pos,41.96,Tyler,Garcia,M,408 Bradley Rest,Doe Hill,...,38.4207,-79.4629,99,Dance movement psychotherapist,3/28/1986,a41d7549acf90789359a9aa5346dcb46,1325376186,38.674999,-78.632459,0

In [ ]:
df.dtypes

trans_date_trans_time    datetime64[ns]
cc_num                          float64
merchant                         object
category                         object
amt                             float64
first                            object
last                             object
gender                           object
street                           object
city                             object
state                            object
zip                               int64
lat                             float64
long                            float64
city_pop                          int64
job                              object
dob                              object
trans_num                        object
unix_time                         int64
merch_lat                       float64
merch_long                      float64
is_fraud                          int64
dtype: object

In [ ]:
df.nunique()

trans_date_trans_time     476595
cc_num                       943
merchant                     693
category                      14
amt                        48602
first                        348
last                         479
gender                         2
street                       965
city                         879
state                         51
zip                          952
lat                          950
long                         951
city_pop                     865
job                          493
dob                          950
trans_num                1048575
unix_time                1030650
merch_lat                1016437
merch_long               1034825
is_fraud                       2
dtype: int64

In [ ]:
df['trans_hour'] = df['trans_date_trans_time'].dt.hour
#deriving 'day of the week'
df['trans_day_of_week'] =df['trans_date_trans_time'].dt.dayofweek + 1
df['trans_day_of_week'] = df['trans_day_of_week'].astype(int)
#deriving 'year_month'
df['trans_year_month'] = df['trans_date_trans_time'].dt.to_period('M')
df.head()

,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,city,...,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud,trans_hour,trans_day_of_week,trans_year_month
0,2019-01-01 00:00:00,2.703190e+15,"fraud_Rippin, Kub and Mann",misc_net,4.97,Jennifer,Banks,F,561 Perry Cove,Moravian Falls,...,"Psychologist, counselling",3/9/1988,0b242abb623afc578575680df30655b9,1325376018,36.011293,-82.048315,0,0,2,2019-01
1,2019-01-01 00:00:00,6.304230e+11,"fraud_Heller, Gutmann and Zieme",grocery_pos,107.23,Stephanie,Gill,F,43039 Riley Greens Suite 393,Orient,...,Special educational needs teacher,6/21/1978,1f76529f8574734946361c461b024d99,1325376044,49.159047,-118.186462,0,0,2,2019-01
2,2019-01-01 00:00:00,3.885950e+13,fraud_Lind-Buckridge,entertainment,220.11,Edward,Sanchez,M,594 White Dale Suite 530,Malad City,...,Nature conservation officer,1/19/1962,a1a22d70485983eac12b5b88dad1cf95,1325376051,43.150704,-112.154481,0,0,2,2019-01
3,2019-01-01 00:01:00,3.534090e+15,"fraud_Kutch, Hermiston and Farrell",gas_transport,45.00,Jeremy,White,M,9443 Cynthia Court Apt. 038,Boulder,...,Patent attorney,1/12/1967,6b849c168bdad6f867558c3793159a81,1325376076,47.034331,-112.561071,0,0,2,2019-01
4,2019-01-01 00:03:00,3.755340e+14,fraud_Keeling-Crist,misc_pos,41.96,Tyler,Garcia,M,408 Bradley Rest,Doe Hill,...,Dance movement psychotherapist,3/28/1986,a41d7549acf90789359a9aa5346dcb46,1325376186,38.674999,-78.632459,0,0,2,2019-01

In [ ]:
df['dob'] = pd.to_datetime(df['dob'])
df['age'] = ((df['trans_date_trans_time'] - df['dob']).dt.days / 365.25).astype(int)

df['age'].head()

0    30
1    40
2    56
3    51
4    32
Name: age, dtype: int64

In [ ]:
df.drop(['trans_date_trans_time','first', 'last', 'dob'] , axis=1, inplace=True)
df.head()

,cc_num,merchant,category,amt,gender,street,city,state,zip,lat,...,job,trans_num,unix_time,merch_lat,merch_long,is_fraud,trans_hour,trans_day_of_week,trans_year_month,age
0,2.703190e+15,"fraud_Rippin, Kub and Mann",misc_net,4.97,F,561 Perry Cove,Moravian Falls,NC,28654,36.0788,...,"Psychologist, counselling",0b242abb623afc578575680df30655b9,1325376018,36.011293,-82.048315,0,0,2,2019-01,30
1,6.304230e+11,"fraud_Heller, Gutmann and Zieme",grocery_pos,107.23,F,43039 Riley Greens Suite 393,Orient,WA,99160,48.8878,...,Special educational needs teacher,1f76529f8574734946361c461b024d99,1325376044,49.159047,-118.186462,0,0,2,2019-01,40
2,3.885950e+13,fraud_Lind-Buckridge,entertainment,220.11,M,594 White Dale Suite 530,Malad City,ID,83252,42.1808,...,Nature conservation officer,a1a22d70485983eac12b5b88dad1cf95,1325376051,43.150704,-112.154481,0,0,2,2019-01,56
3,3.534090e+15,"fraud_Kutch, Hermiston and Farrell",gas_transport,45.00,M,9443 Cynthia Court Apt. 038,Boulder,MT,59632,46.2306,...,Patent attorney,6b849c168bdad6f867558c3793159a81,1325376076,47.034331,-112.561071,0,0,2,2019-01,51
4,3.755340e+14,fraud_Keeling-Crist,misc_pos,41.96,M,408 Bradley Rest,Doe Hill,VA,24433,38.4207,...,Dance movement psychotherapist,a41d7549acf90789359a9aa5346dcb46,1325376186,38.674999,-78.632459,0,0,2,2019-01,32

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1048575 entries, 0 to 1048574
Data columns (total 22 columns):
 #   Column             Non-Null Count    Dtype
---  ------             --------------    -----
 0   cc_num             1048575 non-null  float64
 1   merchant           1048575 non-null  object
 2   category           1048575 non-null  object
 3   amt                1048575 non-null  float64
 4   gender             1048575 non-null  object
 5   street             1048575 non-null  object
 6   city               1048575 non-null  object
 7   state              1048575 non-null  object
 8   zip                1048575 non-null  int64
 9   lat                1048575 non-null  float64
 10  long               1048575 non-null  float64
 11  city_pop           1048575 non-null  int64
 12  job                1048575 non-null  object
 13  trans_num          1048575 non-null  object
 14  unix_time          1048575 non-null  int64
 15  merch_lat          1048575 non-null  float64
 16  merch_long         1048575 non-null  float64
 17  is_fraud           1048575 non-null  int64
 18  trans_hour         1048575 non-null  int32
 19  trans_day_of_week  1048575 non-null  int64
 20  trans_year_month   1048575 non-null  period[M]
 21  age                1048575 non-null  int64
dtypes: float64(6), int32(1), int64(6), object(8), period[M](1)
memory usage: 172.0+ MB

In [ ]:
df['category'] =df['category'].astype('category')
df['gender'] = df['gender'].astype('category')
df['is_fraud'] =df['is_fraud'].astype('category')

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1048575 entries, 0 to 1048574
Data columns (total 22 columns):
 #   Column             Non-Null Count    Dtype
---  ------             --------------    -----
 0   cc_num             1048575 non-null  float64
 1   merchant           1048575 non-null  object
 2   category           1048575 non-null  category
 3   amt                1048575 non-null  float64
 4   gender             1048575 non-null  category
 5   street             1048575 non-null  object
 6   city               1048575 non-null  object
 7   state              1048575 non-null  object
 8   zip                1048575 non-null  int64
 9   lat                1048575 non-null  float64
 10  long               1048575 non-null  float64
 11  city_pop           1048575 non-null  int64
 12  job                1048575 non-null  object
 13  trans_num          1048575 non-null  object
 14  unix_time          1048575 non-null  int64
 15  merch_lat          1048575 non-null  float64
 16  merch_long         1048575 non-null  float64
 17  is_fraud           1048575 non-null  category
 18  trans_hour         1048575 non-null  int32
 19  trans_day_of_week  1048575 non-null  int64
 20  trans_year_month   1048575 non-null  period[M]
 21  age                1048575 non-null  int64
dtypes: category(3), float64(6), int32(1), int64(5), object(6), period[M](1)
memory usage: 151.0+ MB

In [ ]:
df.shape

(1048575, 22)

In [ ]:
df.describe()

,cc_num,amt,zip,lat,long,city_pop,unix_time,merch_lat,merch_long,trans_hour,trans_day_of_week,age
count,1.048575e+06,1.048575e+06,1.048575e+06,1.048575e+06,1.048575e+06,1.048575e+06,1.048575e+06,1.048575e+06,1.048575e+06,1.048575e+06,1.048575e+06,1.048575e+06
mean,4.171565e+17,7.027910e+01,4.880159e+04,3.853336e+01,-9.022626e+01,8.905776e+04,1.344906e+09,3.853346e+01,-9.022648e+01,1.280077e+01,4.135594e+00,4.538658e+01
std,1.308811e+18,1.599518e+02,2.689804e+04,5.076852e+00,1.375858e+01,3.024351e+05,1.019700e+07,5.111233e+00,1.377093e+01,6.816861e+00,2.200499e+00,1.738087e+01
min,6.041621e+10,1.000000e+00,1.257000e+03,2.002710e+01,-1.656723e+02,2.300000e+01,1.325376e+09,1.902779e+01,-1.666712e+02,0.000000e+00,1.000000e+00,1.300000e+01
25%,1.800400e+14,9.640000e+00,2.623700e+04,3.462050e+01,-9.679800e+01,7.430000e+02,1.336682e+09,3.472954e+01,-9.689864e+01,7.000000e+00,2.000000e+00,3.200000e+01
50%,3.520550e+15,4.745000e+01,4.817400e+04,3.935430e+01,-8.747690e+01,2.456000e+03,1.344902e+09,3.936295e+01,-8.743923e+01,1.400000e+01,4.000000e+00,4.300000e+01
75%,4.642260e+15,8.305000e+01,7.204200e+04,4.194040e+01,-8.015800e+01,2.032800e+04,1.354366e+09,4.195602e+01,-8.023228e+01,1.900000e+01,6.000000e+00,5.600000e+01
max,4.992350e+18,2.894890e+04,9.978300e+04,6.669330e+01,-6.795030e+01,2.906700e+06,1.362932e+09,6.751027e+01,-6.695090e+01,2.300000e+01,7.000000e+00,9.500000e+01

In [ ]:
# Convert all numeric columns to numeric type
numeric_cols = df.select_dtypes(include=['number']).columns
df[numeric_cols] = df[numeric_cols].apply(pd.to_numeric, errors='coerce')

# Recalculate five number summary
five_num_summary = {
    'Minimum': df[numeric_cols].min(),
    'Q1 (25th percentile)': df[numeric_cols].quantile(0.25),
    'Median (Q2 - 50th percentile)': df[numeric_cols].median(),
    'Q3 (75th percentile)': df[numeric_cols].quantile(0.75),
    'Maximum': df[numeric_cols].max()
}

# ... (rest of the code remains the same)

In [ ]:
data=numeric_cols
# Five Number Summary
five_num_summary = {
    'Minimum': np.min(numeric_cols),
    'Q1 (25th percentile)': np.percentile(numeric_cols, 25),
    'Median (Q2 - 50th percentile)': np.median(data),
    'Q3 (75th percentile)': np.percentile(data, 75),
    'Maximum': np.max(data)
}

# Mode
mode_value = stats.mode(data)

# Midrange
midrange = (np.min(data) + np.max(data)) / 2

# Outlier Detection using Quartile method
Q1 = five_num_summary['Q1 (25th percentile)']
Q3 = five_num_summary['Q3 (75th percentile)']
IQR = Q3 - Q1
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR
outliers = data[(data < lower_bound) | (data > upper_bound)]

# Printing the results
print("Five Number Summary:")
for key, value in five_num_summary.items():
    print(f"{key}: {value}")

print("\nMode:")
print(f"Mode: {mode_value.mode[0]}, Count: {mode_value.count[0]}")

print("\nMidrange:")
print(midrange)

print("\nOutliers Detected:")
print(outliers)

# Additional statistics (for comparison)
mean = np.mean(data)
std_dev = np.std(data)
print("\nAdditional Statistics:")
print(f"Mean: {mean}")
print(f"Standard Deviation: {std_dev}")

UFuncTypeError: ufunc 'subtract' did not contain a loop with signature matching types (dtype('<U8'), dtype('<U6')) -> None

In [ ]:
data=df
# Five Number Summary
five_num_summary = {
    'Minimum': np.min(data),
    'Q1 (25th percentile)': np.percentile(data, 25),
    'Median (Q2 - 50th percentile)': np.median(data),
    'Q3 (75th percentile)': np.percentile(data, 75),
    'Maximum': np.max(data)
}

# Mode
mode_value = stats.mode(data)

# Midrange
midrange = (np.min(data) + np.max(data)) / 2

# Outlier Detection using Quartile method
Q1 = five_num_summary['Q1 (25th percentile)']
Q3 = five_num_summary['Q3 (75th percentile)']
IQR = Q3 - Q1
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR
outliers = data[(data < lower_bound) | (data > upper_bound)]

# Printing the results
print("Five Number Summary:")
for key, value in five_num_summary.items():
    print(f"{key}: {value}")

print("\nMode:")
print(f"Mode: {mode_value.mode[0]}, Count: {mode_value.count[0]}")

print("\nMidrange:")
print(midrange)

print("\nOutliers Detected:")
print(outliers)

# Additional statistics (for comparison)
mean = np.mean(data)
std_dev = np.std(data)
print("\nAdditional Statistics:")
print(f"Mean: {mean}")
print(f"Standard Deviation: {std_dev}")

TypeError: '<=' not supported between instances of 'int' and 'str'

In [ ]:
import numpy as np
import pandas as pd
from scipy import stats

# ... Your previous code to load and clean the dataset

data = df.select_dtypes(include=np.number) # Select only numeric columns

# Five Number Summary
five_num_summary = {
    'Minimum': np.min(data),
    'Q1 (25th percentile)': np.percentile(data, 25),
    'Median (Q2 - 50th percentile)': np.median(data),
    'Q3 (75th percentile)': np.percentile(data, 75),
    'Maximum': np.max(data)
}

# Mode
# For mode calculation, you might want to consider doing it per column
# as the mode might not be meaningful across all numeric columns
mode_values = {col: stats.mode(data[col]) for col in data.columns}

# Midrange
midrange = (np.min(data) + np.max(data)) / 2

# Outlier Detection using Quartile method
Q1 = five_num_summary['Q1 (25th percentile)']
Q3 = five_num_summary['Q3 (75th percentile)']
IQR = Q3 - Q1
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR
outliers = data[(data < lower_bound) | (data > upper_bound)]

# Printing the results
print("Five Number Summary:")
for key, value in five_num_summary.items():
    print(f"{key}: {value}")

print("\nMode (per column):")
for col, mode in mode_values.items():
    if isinstance(mode.mode, np.ndarray):  # Check if mode is an array
        print(f"Column {col}: Mode: {mode.mode[0]}, Count: {mode.count[0]}")
    else:
        print(f"Column {col}: Mode: {mode.mode}, Count: {mode.count}")  # Handle scalar mode

print("\nMidrange:")
print(midrange)

print("\nOutliers Detected (consider checking per column):")
print(outliers)

# Additional statistics (for comparison)
mean = np.mean(data)
std_dev = np.std(data)
print("\nAdditional Statistics:")
print(f"Mean: {mean}")
print(f"Standard Deviation: {std_dev}")

Five Number Summary:
Minimum: -166.670132
Q1 (25th percentile): 0.0
Median (Q2 - 50th percentile): 48.8856
Q3 (75th percentile): 67635.0
Maximum: 4.99235e+18

Mode (per column):
Column Index: Mode: 0, Count: 1
Column cc_num: Mode: 6011370000000000.0, Count: 395
Column amt: Mode: 1.48, Count: 47
Column zip: Mode: 48088.0, Count: 264
Column lat: Mode: 42.5164, Count: 264
Column long: Mode: -82.9832, Count: 264
Column city_pop: Mode: 1312922.0, Count: 397
Column unix_time: Mode: 1325436739.0, Count: 3
Column merch_lat: Mode: 27.253372, Count: 2
Column merch_long: Mode: -123.346382, Count: 2
Column is_fraud: Mode: 0.0, Count: 93763

Midrange:
2.496175e+18

Outliers Detected (consider checking per column):
       Index        cc_num  amt  zip  lat  long  city_pop     unix_time  \
0        NaN  2.703190e+15  NaN  NaN  NaN   NaN       NaN  1.325376e+09
1        NaN  6.304230e+11  NaN  NaN  NaN   NaN       NaN  1.325376e+09
2        NaN  3.885950e+13  NaN  NaN  NaN   NaN       NaN  1.325376e+09
3        NaN  3.534090e+15  NaN  NaN  NaN   NaN       NaN  1.325376e+09
4        NaN  3.755340e+14  NaN  NaN  NaN   NaN       NaN  1.325376e+09
...      ...           ...  ...  ...  ...   ...       ...           ...
94671    NaN  6.011720e+15  NaN  NaN  NaN   NaN       NaN  1.330180e+09
94672    NaN  4.514240e+15  NaN  NaN  NaN   NaN       NaN  1.330180e+09
94673    NaN  3.553630e+15  NaN  NaN  NaN   NaN       NaN  1.330180e+09
94674    NaN  4.220350e+12  NaN  NaN  NaN   NaN       NaN  1.330180e+09
94675    NaN  4.220500e+18  NaN  NaN  NaN   NaN  233717.0  1.330180e+09

       merch_lat  merch_long  is_fraud
0            NaN         NaN       NaN
1            NaN         NaN       NaN
2            NaN         NaN       NaN
3            NaN         NaN       NaN
4            NaN         NaN       NaN
...          ...         ...       ...
94671        NaN         NaN       NaN
94672        NaN         NaN       NaN
94673        NaN         NaN       NaN
94674        NaN         NaN       NaN
94675        NaN         NaN       NaN

[94676 rows x 11 columns]

Additional Statistics:
Mean: 3.805638018076513e+16
Standard Deviation: Index         2.733061e+04
cc_num        1.310197e+18
amt           1.460468e+02
zip           2.691187e+04
lat           5.079749e+00
long          1.378634e+01
city_pop      3.024554e+05
unix_time     1.383806e+06
merch_lat     5.113223e+00
merch_long    1.379812e+01
is_fraud      9.772625e-02
dtype: float64

/usr/local/lib/python3.10/dist-packages/numpy/core/fromnumeric.py:3643: FutureWarning: The behavior of DataFrame.std with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  return std(axis=axis, dtype=dtype, out=out, ddof=ddof, **kwargs)